# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: java 11 com maven

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Release version ${{ github.event.inputs.releaseversion }}!"
