# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: java 11 com maven

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Release version ${{ github.event.inputs.releaseversion }}!"
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}" --no-transfer-progress
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v2.0.0
      with:
        myToken: ${{ secrets.GH_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.releaseversion }}
        release_name: ${{ github.event.inputs.releaseversion }}
        draft: false
        prerelease: false
